### PR TITLE
Issue#78

### LINKED ISSUE #78: Adding footer

### PR DESCRIPTION
**Pull request by siri0314**
Copyright notice placed in the footer of the website to indicate the year of development and assert intellectual property rights for legal protection and transparency.

Close issue#78

### CODE REVIEW

**Comment by Shirini4** [comment]
Looks good. Aligned at middle. Important information so others don't copy.

**Review by sushmithakishor23 — APPROVED** [review]
Nice job adding the CSS for the faculty home page! I think it looks great and it'll make the page look much more organized and professional. Let me know if you need any help with adding any additional styling.

**Comment by siri0314** [comment]
This issue is resolved with [Footer.jsx](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/blob/main/quiz-game/src/Components/Footer.jsx) code and is [tested](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/pull/87) with automation testing as well.

Program by contract is achieved too.

pre condition: Definition of done
post condition:  [Footer.jsx](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/blob/main/quiz-game/src/Components/Footer.jsx)

validation(pre condition =post condition) is done with [unit testing](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/pull/87)

**Comment by siri0314** [comment]
image

**Pull request merged**
