### PR TITLE
Close issue#42

### LINKED ISSUE #42: Creating signin page
Definition of done:
Created a web page to sign in.

### LINKED ISSUE #44: Adding styles to Sign In page
Definition of Done:
Cascading style sheets are added to sign in page to good view.

### PR DESCRIPTION
**Pull request by siri0314**
Sign in web page is added along with cascading styles sheet to style sign In page.

### CODE REVIEW

**Review by HarshaBojanki3 — CHANGES_REQUESTED** [review]
Need a change in routes.jsx

**Review by siri0314 — COMMENTED** [review]
Reverified

**Review by Shirini4 — APPROVED** [review]
reviwed

**Review by HarshaBojanki3 — APPROVED** [review]
Reviewed

**Comment by WSUCEG7140** [comment]
> Need a change in routes.jsx

What needs to change? What should it change to?

**Comment by siri0314** [comment]
This issue is resolved with [signIn.jsx](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/blob/main/quiz-game/src/Components/SignIn.jsx) code and it is tested with [automation testing](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/pull/97) as well.

Program by contract is achieved too.

pre condition: Definition of done
post condition: [signIn.jsx](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/blob/main/quiz-game/src/Components/SignIn.jsx)

validation(pre condition =post condition) is done with unit [testing](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/pull/97).

**Comment by siri0314** [comment]
image

**Pull request merged**
