### PR TITLE
close issue#92

### LINKED ISSUE #92: Add Unit testing for Navbar

### PR DESCRIPTION
**Pull request by siri0314**
Added Unit testing for navbar. It is important to check if the functionality.

### CODE REVIEW

**Review by sravyakavuru4 — APPROVED** [review]
Testing ensure all the components are up to the mark. good job

**Comment by MummanaTeja** [comment]
everything looks good.

**Comment by siri0314** [comment]
Navbar component is resolved with [Navbar.jsx](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/blob/main/quiz-game/src/Components/Navbar.jsx) code and is tested with [automation testing](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/pull/94) as well.

Program by contract is achieved too.

pre condition: Definition of done
post condition:   [Navbar.jsx](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/blob/main/quiz-game/src/Components/Navbar.jsx)

validation(pre condition =post condition) is done with [automation testing](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/pull/94) as well.

**Comment by siri0314** [comment]
image

**Pull request merged**
